#!/bin/ash

function get_arch () {
  case "$1" in
      x86_64)
          echo "linux/amd64"
          exit;;
      aarch64)
          echo "linux/arm64"
          exit;;
       armv7)
          echo "linux/arm/v7"
          exit;;
      ppc64le)
          echo "linux/ppc64le"
          exit;;
      s390x)
          echo "linux/s390x"
          exit;;
      x86)
          echo "linux/386"
          exit;;
  esac
}

function arch_list () {
  for arc in "$@"; do
    echo -n "$(get_arch "${arc}"),"
  done
}

function make_tags () {
  IMGS=$(echo "$1" | awk 'BEGIN{RS=","} {print}')
  TAGS=$(echo "$2" | awk 'BEGIN{RS=","} {print}')
  for tag in ${TAGS}; do
    for img in ${IMGS}; do
      echo -n "-t ${img}:${tag} "
    done
  done
}

if [ "$1" = "arch" ]; then
  get_arch "$2"
elif [ "$1" == "archlist" ]; then
  shift
  arch_list "${@}" | head -c -1
else
  make_tags "$1" "$2"
fi
